<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Statistical Inference | Module 1</title>
  <meta name="description" content="Chapter 7 Statistical Inference | Module 1" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Statistical Inference | Module 1" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Statistical Inference | Module 1" />
  
  
  

<meta name="author" content="" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hypothesis-testing-and-introduction-to-linear-regression.html"/>
<link rel="next" href="multivariate-data-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIOSCI 220: Quantitative Biology</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Nau mai, haere mai. Welcome to BIOSCI 220!</a></li>
<li class="chapter" data-level="" data-path="key-information.html"><a href="key-information.html"><i class="fa fa-check"></i>Key Information</a>
<ul>
<li class="chapter" data-level="" data-path="key-information.html"><a href="key-information.html#course-outline"><i class="fa fa-check"></i>Course outline</a></li>
<li class="chapter" data-level="" data-path="key-information.html"><a href="key-information.html#r-and-rstudio"><i class="fa fa-check"></i><code>R</code> and <code>RStudio</code></a></li>
<li class="chapter" data-level="" data-path="key-information.html"><a href="key-information.html#your-teaching-team"><i class="fa fa-check"></i>Your teaching team</a></li>
<li class="chapter" data-level="" data-path="key-information.html"><a href="key-information.html#lectures"><i class="fa fa-check"></i>Lectures</a></li>
<li class="chapter" data-level="" data-path="key-information.html"><a href="key-information.html#assessment"><i class="fa fa-check"></i>Assessment</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="r-and-rstudio-1.html"><a href="r-and-rstudio-1.html"><i class="fa fa-check"></i><b>1</b> <code>R</code> and <code>RStudio</code></a>
<ul>
<li class="chapter" data-level="1.1" data-path="r-and-rstudio-1.html"><a href="r-and-rstudio-1.html#what-are-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> What are <code>R</code> and <code>RStudio</code>?</a></li>
<li class="chapter" data-level="1.2" data-path="r-and-rstudio-1.html"><a href="r-and-rstudio-1.html#getting-started-with-r"><i class="fa fa-check"></i><b>1.2</b> Getting started with <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangling-and-manipulation.html"><a href="data-wrangling-and-manipulation.html"><i class="fa fa-check"></i><b>2</b> Data wrangling and manipulation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-wrangling-and-manipulation.html"><a href="data-wrangling-and-manipulation.html#exploratory-data-analysis-eda"><i class="fa fa-check"></i><b>2.1</b> Exploratory Data Analysis (EDA)</a></li>
<li class="chapter" data-level="2.2" data-path="data-wrangling-and-manipulation.html"><a href="data-wrangling-and-manipulation.html#data-visualisation"><i class="fa fa-check"></i><b>2.2</b> Data Visualisation</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-practice.html"><a href="data-practice.html"><i class="fa fa-check"></i><b>3</b> Data practice</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-practice.html"><a href="data-practice.html#data-sovereignty"><i class="fa fa-check"></i><b>3.1</b> Data sovereignty</a></li>
<li class="chapter" data-level="3.2" data-path="data-practice.html"><a href="data-practice.html#reproducible-research"><i class="fa fa-check"></i><b>3.2</b> Reproducible research</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html"><i class="fa fa-check"></i><b>4</b> Introduction to the design and analysis of experiments</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#introduction-to-experiments"><i class="fa fa-check"></i><b>4.1</b> Introduction to experiments</a></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#the-three-main-principles-of-experimental-design"><i class="fa fa-check"></i><b>4.2</b> The three (main) principles of experimental design</a></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#some-experimental-designs"><i class="fa fa-check"></i><b>4.3</b> Some experimental designs</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html"><i class="fa fa-check"></i><b>5</b> Introduction to Hypothesis testing</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#randomisation-tests"><i class="fa fa-check"></i><b>5.1</b> Randomisation tests</a></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#what-is-a-p-value"><i class="fa fa-check"></i><b>5.2</b> What is a <em>p-value</em>?</a></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-hypothesis-testing.html"><a href="introduction-to-hypothesis-testing.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>5.3</b> Type I and Type II errors</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypothesis-testing-and-introduction-to-linear-regression.html"><a href="hypothesis-testing-and-introduction-to-linear-regression.html"><i class="fa fa-check"></i><b>6</b> Hypothesis testing and introduction to linear regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hypothesis-testing-and-introduction-to-linear-regression.html"><a href="hypothesis-testing-and-introduction-to-linear-regression.html#learning-outcomes"><i class="fa fa-check"></i><b>6.1</b> Learning outcomes</a></li>
<li class="chapter" data-level="6.2" data-path="hypothesis-testing-and-introduction-to-linear-regression.html"><a href="hypothesis-testing-and-introduction-to-linear-regression.html#hypothesis-testing"><i class="fa fa-check"></i><b>6.2</b> Hypothesis testing</a></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-testing-and-introduction-to-linear-regression.html"><a href="hypothesis-testing-and-introduction-to-linear-regression.html#model-assumptions"><i class="fa fa-check"></i><b>6.3</b> Model assumptions</a></li>
<li class="chapter" data-level="6.4" data-path="hypothesis-testing-and-introduction-to-linear-regression.html"><a href="hypothesis-testing-and-introduction-to-linear-regression.html#model-diagnostic-plots"><i class="fa fa-check"></i><b>6.4</b> Model diagnostic plots</a></li>
<li class="chapter" data-level="6.5" data-path="hypothesis-testing-and-introduction-to-linear-regression.html"><a href="hypothesis-testing-and-introduction-to-linear-regression.html#other-resources-optional-but-recommended"><i class="fa fa-check"></i><b>6.5</b> Other resources: optional but recommended</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>7</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="7.1" data-path="statistical-inference.html"><a href="statistical-inference.html#learning-outcomes-1"><i class="fa fa-check"></i><b>7.1</b> Learning Outcomes</a></li>
<li class="chapter" data-level="7.2" data-path="statistical-inference.html"><a href="statistical-inference.html#linear-regression"><i class="fa fa-check"></i><b>7.2</b> Linear Regression</a></li>
<li class="chapter" data-level="7.3" data-path="statistical-inference.html"><a href="statistical-inference.html#model-comparison-selection-and-checking-again"><i class="fa fa-check"></i><b>7.3</b> Model comparison, selection, and checking (again)</a></li>
<li class="chapter" data-level="7.4" data-path="statistical-inference.html"><a href="statistical-inference.html#confidence-intervals-and-point-predictions"><i class="fa fa-check"></i><b>7.4</b> Confidence intervals and point predictions</a></li>
<li class="chapter" data-level="7.5" data-path="statistical-inference.html"><a href="statistical-inference.html#tldr-lm"><i class="fa fa-check"></i><b>7.5</b> TL;DR <code>lm()</code></a></li>
<li class="chapter" data-level="7.6" data-path="statistical-inference.html"><a href="statistical-inference.html#other-resources-optional-but-recommended-1"><i class="fa fa-check"></i><b>7.6</b> Other resources: optional but recommended</a></li>
<li class="chapter" data-level="7.7" data-path="statistical-inference.html"><a href="statistical-inference.html#beyond-linear-models-to-generalised-linear-models-glms-not-examinable"><i class="fa fa-check"></i><b>7.7</b> Beyond Linear Models to Generalised Linear Models (GLMs) (<em>not examinable</em>)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html"><i class="fa fa-check"></i><b>8</b> Multivariate Data Analysis</a>
<ul>
<li class="chapter" data-level="8.1" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#learning-outcomes-2"><i class="fa fa-check"></i><b>8.1</b> Learning Outcomes</a></li>
<li class="chapter" data-level="8.2" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#what-is-multivariate-data"><i class="fa fa-check"></i><b>8.2</b> What is multivariate data?</a></li>
<li class="chapter" data-level="8.3" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#dimension-reduction"><i class="fa fa-check"></i><b>8.3</b> Dimension reduction</a></li>
<li class="chapter" data-level="8.4" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#distance-matrices-and-measures"><i class="fa fa-check"></i><b>8.4</b> Distance matrices and measures</a></li>
<li class="chapter" data-level="8.5" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#why-is-nmds-used-frequently-in-biology"><i class="fa fa-check"></i><b>8.5</b> Why is nMDS used frequently in biology?</a></li>
<li class="chapter" data-level="8.6" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#steps-to-nmds"><i class="fa fa-check"></i><b>8.6</b> Steps to nMDS</a></li>
<li class="chapter" data-level="8.7" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#nmds-in-r-using-metamds-on-the-palmerpenguins-data-set"><i class="fa fa-check"></i><b>8.7</b> nMDS in <code>R</code> using <code>metaMDS()</code> on the <code>palmerpenguins</code> data set</a></li>
<li class="chapter" data-level="8.8" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#diagnostic-plots-for-nmds"><i class="fa fa-check"></i><b>8.8</b> Diagnostic plots for nMDS</a></li>
<li class="chapter" data-level="8.9" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#how-to-interpret-an-nmds-plot-and-what-to-report"><i class="fa fa-check"></i><b>8.9</b> How to interpret an nMDS plot and what to report</a></li>
<li class="chapter" data-level="8.10" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#nmds-in-r-using-metamds-with-community-structure-data"><i class="fa fa-check"></i><b>8.10</b> nMDS in <code>R</code> using <code>metaMDS()</code> with community structure data</a></li>
<li class="chapter" data-level="8.11" data-path="multivariate-data-analysis.html"><a href="multivariate-data-analysis.html#other-resources-optional-but-recommended-2"><i class="fa fa-check"></i><b>8.11</b> Other resources: optional but recommended</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://canvas.auckland.ac.nz/courses/104039">CANVAS</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Module 1</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistical-inference" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Statistical Inference<a href="statistical-inference.html#statistical-inference" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="learning-outcomes-1" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Learning Outcomes<a href="statistical-inference.html#learning-outcomes-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Write <code>R</code> code to fit a linear regression model, and interpret estimated coefficients of these models:
<ul>
<li>a single categorical explanatory variable (using dummy variables)</li>
<li>no explanatory variable (a null model)</li>
<li>a single continuous explanatory variable</li>
<li>a continuous and a categorical factor explanatory variable</li>
<li>an interaction term in the explanatory variables</li>
</ul></li>
<li>Explain why you may want to include interaction terms in a model.</li>
<li>Describe the differences between the operators <code>:</code> and <code>*</code> in an <code>R</code> model-fitting formula</li>
<li>Demonstrate how to make point predictions from linear regression models, specifically models with:
<ul>
<li>a single continuous explanatory variable</li>
<li>a continuous and a categorical factor explanatory variable</li>
<li>an interaction term in the explanatory variables</li>
</ul></li>
<li>Understand how to undertake model selection using the <code>anova()</code> and <code>AIC()</code> functions in R and interpret the output</li>
<li>Compute confidence intervals in <code>R</code> to estimate a population parameter, and interpret their meaning</li>
</ul>
</div>
<div id="linear-regression" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Linear Regression<a href="statistical-inference.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="https://raw.githubusercontent.com/cmjt/statbiscuits/master/figs_n_gifs/lm.gif" /></p>
<div id="some-mathematical-notation" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Some mathematical notation<a href="statistical-inference.html#some-mathematical-notation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s consider a linear regression with a single explanatory variable. This is what the model looks like:</p>
<p><span class="math display">\[Y_i = \alpha + \beta_1x_i + \epsilon_i\]</span>
where</p>
<p><span class="math display">\[\epsilon_i \sim \text{Normal}(0,\sigma^2).\]</span></p>
<p>Here for observation <span class="math inline">\(i\)</span></p>
<ul>
<li><span class="math inline">\(Y_i\)</span> is the value of the response</li>
<li><span class="math inline">\(x_i\)</span> is the value of the explanatory variable</li>
<li><span class="math inline">\(\epsilon_i\)</span> is the error term: the difference between <span class="math inline">\(Y_i\)</span> and its expected value</li>
<li><span class="math inline">\(\alpha\)</span> is the intercept term (a parameter to be estimated), and</li>
<li><span class="math inline">\(\beta_1\)</span> is the slope: coefficient of the explanatory variable (a parameter to be estimated)</li>
</ul>
<p>Note: you may also see the intercept term <span class="math inline">\(\alpha\)</span> written as <span class="math inline">\(\beta_0\)</span></p>
<p>Does this remind you of anything?</p>
<p><img src="https://memegenerator.net/img/instances/63099571/one-does-not-simply-forget-ymxc.jpg" /></p>
</div>
<div id="modelling-bill-depth" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Modelling Bill Depth<a href="statistical-inference.html#modelling-bill-depth" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the following statistical inference sections, we will be working with our <code>palmerpenguins</code> data set, where we are interested in examining a few different linear regression models with a different numbers of explanatory variables that may help us explain the variation in bill depth <code>bill_depth_mm</code>, our response variable. We will start with the simplest model, with no explanatory variables, and then add in more explanatory variables (both categorical and continuous) and alter the way they interact with each other in the model, while seeing how to use this sample data to draw inferences about the underlying population.</p>
<p><img src="https://cran.r-project.org/web/packages/palmerpenguins/readme/man/figures/culmen_depth.png" /></p>
<p>Let’s take a look at the bill depth data in a histogram (it’s always nice to have a visual!).</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="statistical-inference.html#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb128-2"><a href="statistical-inference.html#cb128-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb128-3"><a href="statistical-inference.html#cb128-3" aria-hidden="true" tabindex="-1"></a>penguins_nafree <span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span></code></pre></div>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="statistical-inference.html#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins_nafree, <span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm)) <span class="sc">+</span></span>
<span id="cb129-2"><a href="statistical-inference.html#cb129-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb129-3"><a href="statistical-inference.html#cb129-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Bill depth (mm)&quot;</span>)</span></code></pre></div>
<p><img src="BIOSCI220_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<p>First off let’s fit a null (intercept only, no slope) model. This in <em>old money</em> would be called a one sample t-test.</p>
<p><strong>Model formula</strong></p>
<p>The null model formula is: <span class="math display">\[Y_i = \alpha + \epsilon_i.\]</span></p>
<p>Here for observation <span class="math inline">\(i\)</span>, <span class="math inline">\(Y_i\)</span> is the value of the response (<code>bill_depth_mm</code>) and <span class="math inline">\(\alpha\)</span> is a parameter to be estimated (typically called the intercept).</p>
<p>The <code>R</code> code for this model specifies a <code>1</code> to represent a constant, as we have no explanatory variables in this model and there is no slope to estimate.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="statistical-inference.html#cb130-1" aria-hidden="true" tabindex="-1"></a>slm_null <span class="ot">&lt;-</span> <span class="fu">lm</span>(bill_depth_mm <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> penguins_nafree)</span></code></pre></div>
<p>The hypotheses being tested are <span class="math inline">\(H_0:\mu_{\text{bill_depth_mm}} = 0\)</span> vs. <span class="math inline">\(H_1:\mu_{\text{bill_depth_mm}} \neq 0\)</span></p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="statistical-inference.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slm_null)<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##             Estimate Std. Error  t value      Pr(&gt;|t|)
## (Intercept) 17.16486  0.1079134 159.0614 1.965076e-315</code></pre>
<p><strong>So, what are the values/regression coefficients from the <code>lm()</code> output above?</strong></p>
<ul>
<li><code>Estimate</code> of the <code>(Intercept)</code> = 17.1648649, tells us the (estimated) average value of the response (in this example, it is the estimate of the population mean (<span class="math inline">\(\mu\)</span>) of <code>bill_depth_mm</code>), which we can show using the code below:</li>
</ul>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="statistical-inference.html#cb133-1" aria-hidden="true" tabindex="-1"></a>penguins_nafree <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">average_bill_depth =</span> <span class="fu">mean</span>(bill_depth_mm))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   average_bill_depth
##                &lt;dbl&gt;
## 1               17.2</code></pre>
<ul>
<li><p>The SEM (<code>Std. Error</code>) = 0.1079134.</p></li>
<li><p>The t-statistic is given by <code>t value</code> = <code>Estimate</code> / <code>Std. Error</code> = 159.0614207</p></li>
<li><p>The <em>p</em>-value is given by<code>Pr (&gt;|t|)</code> = 1.965076e-315</p></li>
</ul>
<p>So the probability of observing a t-statistic as least as extreme given under the null hypothesis (average bill depth = 0) given our data is 1.965076e-315, pretty strong evidence against the null hypothesis I’d say! I hope this makes sense biologically as we would not expect the average bill depth of a penguin to be 0!</p>
</div>
<div id="single-continuous-explanatory-variable" class="section level3 hasAnchor" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Single continuous explanatory variable<a href="statistical-inference.html#single-continuous-explanatory-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Does <code>bill_length_mm</code> help explain some of the variation in <code>bill_depth_mm</code>?</strong></p>
<p><strong>Model formula</strong></p>
<p>The formula for this model is <span class="math display">\[Y_i = \alpha + \beta_1x_i + \epsilon_i\]</span> where for observation <span class="math inline">\(i\)</span> <span class="math inline">\(Y_i\)</span> is the value of the response (<code>bill_depth_mm</code>) and <span class="math inline">\(x_i\)</span> is the value of the explanatory variable (<code>bill_length_mm</code>); <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta_1\)</span> are population parameters to be estimated using our sample data. We could also write this model as</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{bill\_depth\_mm} &amp;= \alpha + \beta_{1}(\operatorname{bill\_length\_mm}) + \epsilon
\end{aligned}
\]</span></p>
<p><strong>Fitted model</strong></p>
<p>We can output our estimated population parameters (<span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta_1\)</span>) using</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="statistical-inference.html#cb135-1" aria-hidden="true" tabindex="-1"></a>slm <span class="ot">&lt;-</span> <span class="fu">lm</span>(bill_depth_mm <span class="sc">~</span> bill_length_mm, <span class="at">data =</span> penguins_nafree)</span>
<span id="cb135-2"><a href="statistical-inference.html#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slm)<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##                   Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)    20.78664867 0.85417308 24.335406 1.026904e-75
## bill_length_mm -0.08232675 0.01926835 -4.272642 2.528290e-05</code></pre>
<p>The <code>Estimate</code> of the <code>(Intercept)</code> (<span class="math inline">\(\alpha\)</span> in the model) gives us the estimated average bill depth (mm) <strong>given the estimated relationship</strong> between bill length (mm) and bill depth (mm).</p>
<p>The <code>Estimate</code> of <code>bill_length_mm</code> (<span class="math inline">\(\beta_1\)</span> in the model) is the slope associated with bill length (mm). Here for every 1mm increase in bill length we estimated a 0.082 mm decrease (or a -0.082 mm increase) in bill depth.</p>
<p>The plot below shows this relationship visually:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="statistical-inference.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate predicted values</span></span>
<span id="cb137-2"><a href="statistical-inference.html#cb137-2" aria-hidden="true" tabindex="-1"></a>penguins_nafree<span class="sc">$</span>pred_vals <span class="ot">&lt;-</span> <span class="fu">predict</span>(slm)</span>
<span id="cb137-3"><a href="statistical-inference.html#cb137-3" aria-hidden="true" tabindex="-1"></a><span class="do">## plot</span></span>
<span id="cb137-4"><a href="statistical-inference.html#cb137-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins_nafree, <span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> bill_depth_mm)) <span class="sc">+</span></span>
<span id="cb137-5"><a href="statistical-inference.html#cb137-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Bill depth (mm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb137-6"><a href="statistical-inference.html#cb137-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Bill length (mm)&quot;</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb137-7"><a href="statistical-inference.html#cb137-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred_vals))</span></code></pre></div>
<p><img src="BIOSCI220_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
</div>
<div id="a-continuous-and-a-categorical-factor-explanatory-variable-additive-model" class="section level3 hasAnchor" number="7.2.4">
<h3><span class="header-section-number">7.2.4</span> A continuous and a categorical factor explanatory variable (Additive model)<a href="statistical-inference.html#a-continuous-and-a-categorical-factor-explanatory-variable-additive-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Does adding in <code>species</code> to the above model help explain more of the variation in <code>bill_depth_mm</code>?</strong><br />
Remember <code>species</code> is a categorical factor variable with three levels/groups: Adelie, Chinstrap and Gentoo.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="statistical-inference.html#cb138-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> penguins_nafree,</span>
<span id="cb138-2"><a href="statistical-inference.html#cb138-2" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">y =</span> bill_depth_mm, <span class="at">x =</span> bill_length_mm, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb138-3"><a href="statistical-inference.html#cb138-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Bill depth (mm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb138-4"><a href="statistical-inference.html#cb138-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Bill length (mm)&quot;</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>()</span>
<span id="cb138-5"><a href="statistical-inference.html#cb138-5" aria-hidden="true" tabindex="-1"></a>p2</span></code></pre></div>
<p><img src="BIOSCI220_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="statistical-inference.html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co"># notice the + between the two explanatory variables?</span></span>
<span id="cb139-2"><a href="statistical-inference.html#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="co"># this + is what indicates this is an additive model</span></span>
<span id="cb139-3"><a href="statistical-inference.html#cb139-3" aria-hidden="true" tabindex="-1"></a>slm_sp <span class="ot">&lt;-</span> <span class="fu">lm</span>(bill_depth_mm <span class="sc">~</span> bill_length_mm <span class="sc">+</span> species, <span class="at">data =</span> penguins_nafree)</span></code></pre></div>
<p><strong>Model formula</strong></p>
<p>Now we have <strong>two explanatory variables</strong>, if they were both continuous variables, the model formula would be…</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1z_i + \beta_2x_i + \epsilon_i\]</span>
<span class="math display">\[\epsilon_i \sim \text{Normal}(0,\sigma^2)\]</span></p>
<p>where for observation <span class="math inline">\(i\)</span></p>
<ul>
<li><span class="math inline">\(Y_i\)</span> is the value of the response (<code>bill_depth_mm</code>)</li>
<li><span class="math inline">\(z_i\)</span> is one explanatory variable (<code>bill_length_mm</code> say)</li>
<li><span class="math inline">\(x_i\)</span> is another explanatory variable (<code>species</code> say)</li>
<li><span class="math inline">\(\epsilon_i\)</span> is the error term: the difference between <span class="math inline">\(Y_i\)</span> and its expected value</li>
<li><span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span> are all parameters to be estimated.</li>
</ul>
<p>…but because one of the variables is <strong>categorical</strong>, our model formula needs to be written in a slightly more complicated way</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1z_i + \beta_2x_{i,1} + \beta_3x_{i,2} + ... +\beta_kx_{i,k}+ \epsilon_i\]</span>
where the only new terminology from the above formula is</p>
<ul>
<li><span class="math inline">\(x_{i,k}\)</span> is the value of the explanatory variable (where <em>k</em> = # of levels of the variable - 1, as one level is the intercept)</li>
</ul>
<p>Another way to write this model formula for this example is</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{bill\_depth\_mm} &amp;= \alpha + \beta_{1}(\operatorname{bill\_length\_mm}) + \beta_{2}(\operatorname{species}_{\operatorname{Chinstrap}}) + \beta_{3}(\operatorname{species}_{\operatorname{Gentoo}})\ + \\
&amp;\quad \epsilon
\end{aligned}
\]</span></p>
<p>When we have categorical explanatory variables (e.g., <code>species</code>) we have to use <strong>dummy variables</strong> to estimate population parameters in our linear regression model.</p>
<p><em>What is a dummy variable?</em><br />
It is a variable created to assign numerical value to levels of categorical variables. This is necessary with most categorical variables because an individual usually cannot be in more than one group/level (e.g., a Chinstrap penguin cannot be a Gentoo penguin too!). So the dummy variable coding works by representing one category of the explanatory variable and is coded with 1 if the case falls in that category and with 0 if not.</p>
<p>Here’s an example dummy variable table for <code>species</code> in the <code>palmerpenguin</code> data set:</p>
<p><img src="figs/dv_table_penguins.png" /></p>
<p>Here the <code>Adelie</code> group is the baseline (<code>R</code> does this alphabetically by default. To change this, we can use the <code>mutate</code> function. See section 5.2.4.2 in Hypothesis testing for more details) so we assign a 0 to <code>speciesChinstrap</code> and a 0 to <code>speciesGentoo</code> to see what the response is for Adelie penguins <code>(Intercept)</code>. This is shown in the top line row of the table above.</p>
<p><strong>Fitted model</strong></p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="statistical-inference.html#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slm_sp)<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##                    Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)      10.5652616 0.69092642  15.291442 2.977289e-40
## bill_length_mm    0.2004431 0.01767974  11.337449 2.258955e-25
## speciesChinstrap -1.9330779 0.22571878  -8.564099 4.259893e-16
## speciesGentoo    -5.1033153 0.19439523 -26.252267 1.043789e-82</code></pre>
<p>Here, the <code>Estimate</code> of the <code>(Intercept)</code> (<span class="math inline">\(\alpha\)</span> or <span class="math inline">\(\beta_0\)</span> in the model) gives us the estimated average bill depth (mm) of the <strong>Adelie</strong> penguins <strong>given the other variables in the model</strong>.</p>
<p>The <code>Estimate</code> of <code>bill_length_mm</code> (<span class="math inline">\(\beta_1\)</span> in the model) is the slope associated with bill length (mm). So, here for every 1 mm increase in bill length we estimated a 0.2 mm increase in bill depth.</p>
<p>What about the regression coefficients of the other species levels (<code>Estimate</code> for <code>speciesChinstrap</code> and <code>speciesGentoo</code>)? These values give the shift (up or down) of the <strong>parallel</strong> lines from the <strong>Adelie</strong> (<code>(Intercept)</code>) level. So given the estimated relationship between bill depth and bill length these coefficients are the estimated change for each species from the baseline. You can visualise this by looking at the plot below.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="statistical-inference.html#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate predicted values</span></span>
<span id="cb142-2"><a href="statistical-inference.html#cb142-2" aria-hidden="true" tabindex="-1"></a>penguins_nafree<span class="sc">$</span>pred_vals <span class="ot">&lt;-</span> <span class="fu">predict</span>(slm_sp)</span>
<span id="cb142-3"><a href="statistical-inference.html#cb142-3" aria-hidden="true" tabindex="-1"></a><span class="do">## plot</span></span>
<span id="cb142-4"><a href="statistical-inference.html#cb142-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins_nafree, <span class="fu">aes</span>(<span class="at">y =</span> bill_depth_mm, <span class="at">x =</span> bill_length_mm, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb142-5"><a href="statistical-inference.html#cb142-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Bill depth (mm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb142-6"><a href="statistical-inference.html#cb142-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Bill length (mm)&quot;</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>()  <span class="sc">+</span></span>
<span id="cb142-7"><a href="statistical-inference.html#cb142-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred_vals))</span></code></pre></div>
<p><img src="BIOSCI220_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p><strong>Simpson’s paradox…</strong> look how the slope associated with bill length (coefficient of <code>bill_length_mm</code>) has switched direction from the model with just one explanatory variable <code>bill_length_mm</code>! Why do you think this is?</p>
</div>
<div id="a-continuous-and-a-categorical-factor-explanatory-variable-interaction-model" class="section level3 hasAnchor" number="7.2.5">
<h3><span class="header-section-number">7.2.5</span> A continuous and a categorical factor explanatory variable (Interaction model)<a href="statistical-inference.html#a-continuous-and-a-categorical-factor-explanatory-variable-interaction-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall the <em>additive</em> model formula from above</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1z_i + \beta_2x_i + \epsilon_i\]</span>
An additive model will always produce regression lines that are <strong>parallel</strong> with each other (i.e., there is no relationship between the explanatory variables, they act independently of each other)…</p>
<p><strong>…but</strong> we should really check to see if the explanatory variables have relationships with each other (i.e., the explanatory variables do not act independently on the response variable.). If this is the case, the regression lines will <strong>not be parallel</strong> with each other.</p>
<p><strong>Model formula</strong></p>
<p>This is still for two explanatory variables</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1z_i + \beta_2x_{i,1} + \beta_3x_{i,2} + ... +\beta_kx_{i,k}+ \beta_4z_ix_{i,k} + \epsilon_i\]</span>
You’ll notice a new term <span class="math inline">\(\beta_4z_ix_{i,k}\)</span> in this model compared to the additive model. This is the <strong>interaction term</strong> between the two explanatory variables <span class="math inline">\(z_i\)</span> and <span class="math inline">\(x_{i,k}\)</span>.</p>
<p>The model formula for our penguin example can also be written as</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{bill\_depth\_mm} &amp;= \alpha + \beta_{1}(\operatorname{bill\_length\_mm}) + \beta_{2}(\operatorname{species}_{\operatorname{Chinstrap}}) + \beta_{3}(\operatorname{species}_{\operatorname{Gentoo}})\ + \\
&amp;\quad \beta_{4}(\operatorname{bill\_length\_mm} \times \operatorname{species}_{\operatorname{Chinstrap}}) + \beta_{5}(\operatorname{bill\_length\_mm} \times \operatorname{species}_{\operatorname{Gentoo}}) + \epsilon
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(\beta_4\)</span>bill_length_mm x species<sub>Chinstrap</sub> and <span class="math inline">\(\beta_5\)</span>bill_length_mm x species<sub>Gentoo</sub> represent the interaction terms in the model.</p>
<p><em>This is getting pretty complicated already and we only have two explanatory variables!!!</em></p>
<p><em>However, we can add in more explanatory variables, both categorical and/or continuous, with additive and/or interaction terms between variables and the same principles for inference apply. We will practice with slightly more complicated data in our lab assignment this week.</em></p>
<p><strong>Note:</strong> we can include interaction effects in our <code>lm()</code> model in <code>R</code> by using either the <code>*</code> or <code>:</code> syntax in our model formula. For example,</p>
<ul>
<li><p><code>:</code> denotes the interaction only of the variables to its left and right, and</p></li>
<li><p><code>*</code> means to include all main effects and interactions, so <code>a * b</code> is the same as <code>a + b + a:b</code>, where <code>a</code> and <code>b</code> represent the main effects and <code>a:b</code> represents the interaction term in the model.</p></li>
</ul>
<p>To specify a model with additive and interaction effects use either</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="statistical-inference.html#cb143-1" aria-hidden="true" tabindex="-1"></a>slm_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(bill_depth_mm <span class="sc">~</span> bill_length_mm <span class="sc">*</span> species, <span class="at">data =</span> penguins_nafree)</span></code></pre></div>
<p>Or the other way we could write this and get the SAME MODEL is</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="statistical-inference.html#cb144-1" aria-hidden="true" tabindex="-1"></a>slm_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(bill_depth_mm <span class="sc">~</span> bill_length_mm <span class="sc">+</span> species <span class="sc">+</span> </span>
<span id="cb144-2"><a href="statistical-inference.html#cb144-2" aria-hidden="true" tabindex="-1"></a>                bill_length_mm <span class="sc">:</span> species, <span class="at">data =</span> penguins_nafree)</span></code></pre></div>
<p><strong>Fitted model</strong></p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="statistical-inference.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slm_int)<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##                                    Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)                     11.48770713 1.15987305  9.9042797 2.135979e-20
## bill_length_mm                   0.17668344 0.02980564  5.9278518 7.793199e-09
## speciesChinstrap                -3.91856701 2.06730876 -1.8954919 5.890889e-02
## speciesGentoo                   -6.36675118 1.77989710 -3.5770333 4.000274e-04
## bill_length_mm:speciesChinstrap  0.04552828 0.04594283  0.9909769 3.224296e-01
## bill_length_mm:speciesGentoo     0.03092816 0.04111608  0.7522157 4.524625e-01</code></pre>
<p>As before, the <code>Estimate</code> of the <code>(Intercept)</code> gives us the estimated average bill depth (mm) of the <strong>Adelie</strong> penguins <strong>given the other variables in the model</strong>.</p>
<p>The <code>bill_length_mm</code> : <code>Estimate</code> (<span class="math inline">\(\beta_1\)</span> in the model) is the slope associated with bill length (mm). So, here for every 1 mm increase in bill length we estimated a 0.177 mm increase in bill depth.</p>
<p>The main effects of species (i.e., <code>Estimate</code> for <code>speciesChinstrap</code> and <code>speciesGentoo</code>) again give the shift (up or down) of the lines from the <strong>Adelie</strong> level; however these lines are no longer parallel! The interaction terms (i.e., <code>bill_length_mm:speciesChinstrap</code> and <code>bill_length_mm:speciesGentoo</code>) specify the species specific slopes <strong>given the other variables in the model</strong>.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="statistical-inference.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate predicted values</span></span>
<span id="cb147-2"><a href="statistical-inference.html#cb147-2" aria-hidden="true" tabindex="-1"></a>penguins_nafree<span class="sc">$</span>pred_vals <span class="ot">&lt;-</span> <span class="fu">predict</span>(slm_int)</span>
<span id="cb147-3"><a href="statistical-inference.html#cb147-3" aria-hidden="true" tabindex="-1"></a><span class="do">## plot</span></span>
<span id="cb147-4"><a href="statistical-inference.html#cb147-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins_nafree, <span class="fu">aes</span>(<span class="at">y =</span> bill_depth_mm, <span class="at">x =</span> bill_length_mm, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb147-5"><a href="statistical-inference.html#cb147-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Bill depth (mm)&quot;</span>) <span class="sc">+</span></span>
<span id="cb147-6"><a href="statistical-inference.html#cb147-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Bill length (mm)&quot;</span>) <span class="sc">+</span> <span class="fu">theme_classic</span>()  <span class="sc">+</span></span>
<span id="cb147-7"><a href="statistical-inference.html#cb147-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred_vals))</span></code></pre></div>
<p><img src="BIOSCI220_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>Look at the plot above. Now we’ve specified this <em>all singing and dancing</em> interaction model we might ask <strong>are the non-parallel lines non-parallel enough to say this model is better than the parallel line model</strong>?</p>
</div>
</div>
<div id="model-comparison-selection-and-checking-again" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Model comparison, selection, and checking (again)<a href="statistical-inference.html#model-comparison-selection-and-checking-again" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Remember that it is always is imperative that we <strong>check the underlying assumptions</strong> of our model! If our assumptions are not met then basically the maths falls over and we can’t reliably interpret the outputs from the model (e.g., can’t trust the parameter estimates etc.).</p>
<p><strong>Key assumptions of linear regression models</strong></p>
<ul>
<li><strong>Independence</strong></li>
<li>There is a <strong>linear relationship</strong> between the response and the explanatory variables</li>
<li>The residuals have <strong>constant variance</strong></li>
<li>The residuals are <strong>normally distributed</strong></li>
</ul>
<p>Let’s look at the fit of the <code>slm</code> model (single continuous explanatory variable)</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="statistical-inference.html#cb148-1" aria-hidden="true" tabindex="-1"></a>gglm<span class="sc">::</span><span class="fu">gglm</span>(slm) <span class="co"># Plot the four main diagnostic plots</span></span></code></pre></div>
<p><img src="BIOSCI220_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>Do you think the model assumptions have been met? Think of what this model is, do you think it’s the best we can do?</p>
<div id="model-comparison-and-selection" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Model comparison and selection<a href="statistical-inference.html#model-comparison-and-selection" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A good model not only needs to fit data well, it also needs to be parsimonious. That is, a good model should be only be as complex as necessary to describe a data set. If you are choosing between a very simple model with 1 explanatory variable, and a very complex model with, say, 10 explanatory variables, the very complex model needs to provide a much better fit to the data in order to justify its increased complexity. If it can’t, then the simpler model should be preferred. After all, it’s also much easier to interpret a simpler model (look at our increased complexity from just adding the interaction term in a two explanatory variable model)!</p>
<div id="model-comparison-using-anova" class="section level4 hasAnchor" number="7.3.1.1">
<h4><span class="header-section-number">7.3.1.1</span> Model comparison using <code>anova()</code><a href="statistical-inference.html#model-comparison-using-anova" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can compare <strong>nested</strong> linear models using hypothesis testing. Luckily the <code>R</code> function <code>anova()</code> automates this if you input the two regression objects as separate arguments. Yes, it’s the same idea as we’ve previously learnt about ANOVA. We perform an F-test between the nested models!</p>
<p>By <strong>nested</strong> we mean that one model is a subset of the other (i.e., where the coefficients both models have in common cancel each other out, so they are essentially weighted at zero). For example,</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1z_i + \epsilon_i\]</span></p>
<p>is a nested version of</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1z_i + \beta_2x_i + \epsilon_i\]</span>
This ANOVA will test whether or not including <span class="math inline">\(\beta_2x_i\)</span> leads to a significant improvement in the model.</p>
<p>As an example consider testing the single explanatory variable model <code>slm</code> against the same model with <code>species</code> included as a variable <code>slm_sp</code>. To carry out the appropriate hypothesis test in <code>R</code> we can run</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="statistical-inference.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(slm,slm_sp)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: bill_depth_mm ~ bill_length_mm
## Model 2: bill_depth_mm ~ bill_length_mm + species
##   Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    331 1220.16                                  
## 2    329  299.62  2    920.55 505.41 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As you’ll see the <code>anova()</code> function takes two model objects (<code>slm</code> and <code>slm_sp</code>) each as arguments. It returns an ANOVA testing whether the simpler model (<code>slm</code>) is just as good at capturing the variation in the data as the more complex model (<code>slm_sp</code>). The returned p-value should be interpreted as in any other hypothesis test. i.e., the probability of observing a statistic as least as extreme under our null hypothesis (here, that either model is as good as each other at capturing the variation in the data, or model 1 = model 2, or model 1 - model 2 = 0).</p>
<p>What would we conclude here from the output above comparing <code>slm</code> and <code>slm_sp</code>? We can see the results show a <code>Df</code> of <code>2</code> (indicating that the more complex model has two additional parameters) and a very small p-value (&lt;2e-16). I’d say we have very strong evidence against the models being equally good, and adding <code>species</code> to the model lead to a significantly improved fit over <code>slm</code> without <code>species</code>! Looking at the relevant plots, does this make sense?</p>
<p>Now what about <code>slm_int</code> vs <code>slm_sp</code>?
<strong>Are the non-parallel lines non-parallel enough to say the more complicated interaction model is better than the simpler parallel line additive model?</strong></p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="statistical-inference.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(slm_sp,slm_int)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: bill_depth_mm ~ bill_length_mm + species
## Model 2: bill_depth_mm ~ bill_length_mm + species + bill_length_mm:species
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    329 299.62                           
## 2    327 298.62  2   0.99284 0.5436 0.5812</code></pre>
<p>So it seems both models are just as good at capturing the variation in our data: we’re happy with the simpler model with parallel lines!</p>
</div>
<div id="model-comparison-using-aic" class="section level4 hasAnchor" number="7.3.1.2">
<h4><span class="header-section-number">7.3.1.2</span> Model comparison using <code>AIC()</code><a href="statistical-inference.html#model-comparison-using-aic" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Another way we might compare models is by using the Akaike information criterion (AIC) (you’ll see more of this later in the course). AIC is an estimator of out-of-sample prediction error and can be used as a metric to choose between competing models. Lower AIC scores are better, and AIC penalizes models that use more parameters. So if two models explain the same amount of variation, the one with fewer parameters (<code>df</code>) will have a lower AIC value (i.e., smallest out-of-sample prediction error) and will be the better-fit model. Typically, a difference of 4 or more is considered to indicate an improvement; this should not be taken as writ however, using multiple comparison techniques is advised.</p>
<p><code>R</code> has an <code>AIC()</code> function that can be used directly on your <code>lm()</code> model objects. The <code>AIC()</code> function can take multiple arguments compared to <code>anova()</code> that can only compare two models at a time. For example,</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="statistical-inference.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(slm_null, slm, slm_sp, slm_int)</span></code></pre></div>
<pre><code>##          df       AIC
## slm_null  2 1399.3234
## slm       3 1383.4462
## slm_sp    5  919.8347
## slm_int   7  922.7294</code></pre>
<p>This supports what the <code>anova()</code> output suggested; <code>slm_sp</code> is the preferred model. As always it’s important to do a sanity check! Does this make sense? Have a look at the outputs from these models and see what you think.</p>
<p>Just because we’ve chosen a model (<em>the best of a bad bunch</em> perhaps?) this doesn’t let us off the hook. We should check our assumptions…</p>
<p>…well, we should have checked them before we started to interpret the data!</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="statistical-inference.html#cb155-1" aria-hidden="true" tabindex="-1"></a>gglm<span class="sc">::</span><span class="fu">gglm</span>(slm_sp) <span class="co"># Plot the four main diagnostic plots</span></span></code></pre></div>
<p><img src="BIOSCI220_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<p><strong>Residuals vs Fitted</strong> plot: equal spread? Doesn’t look too trumpety/slice of pizza shaped! Don’t worry that there aren’t many points between 16-17 on the x-axis.</p>
<p><strong>Normal quantile-quantile (QQ)</strong> plot: skewed? Maybe slightly right skewed (deviation upwards from the right tail) but probably nothing to worry about.</p>
<p><strong>Scale-Location</strong> plot: equal spread and relatively straight line? I’d say so.</p>
<p><strong>Residuals vs Leverage</strong>: ? Maybe a couple of points with high leverage.</p>
</div>
</div>
</div>
<div id="confidence-intervals-and-point-predictions" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Confidence intervals and point predictions<a href="statistical-inference.html#confidence-intervals-and-point-predictions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far, we’ve got population parameter estimates from our linear regression models (all the <span class="math inline">\(\alpha\)</span>s and <span class="math inline">\(\beta\)</span>s!). We’ve used other statistical tools to check the linear regression model assumptions are met and also selected the best model (in terms of which explanatory variables are most useful, and whether they should be treated as independent from each other (additive) or interacting).
However, there’s a couple more things we might like to do, such as:</p>
<ul>
<li>determine confidence intervals for parameter estimates</li>
<li>make point predictions (i.e., input explanatory variable information to predict the response variable)</li>
</ul>
<div id="confidence-intervals" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Confidence intervals<a href="statistical-inference.html#confidence-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Confidence intervals provide a range of values around a population estimate that are believed to contain, with a certain probability (e.g., 95%), the true value of that estimate. They provide a way to quantify the uncertainty about the value of that population estimate we have calculated from the sample data.</p>
<p>For the <em>chosen</em> <code>slm_sp</code> model we can get the confidence intervals for the regression coefficient estimates in <code>R</code> by using the <code>confint()</code> function.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="statistical-inference.html#cb156-1" aria-hidden="true" tabindex="-1"></a>cis <span class="ot">&lt;-</span> <span class="fu">confint</span>(slm_sp)</span>
<span id="cb156-2"><a href="statistical-inference.html#cb156-2" aria-hidden="true" tabindex="-1"></a>cis</span></code></pre></div>
<pre><code>##                       2.5 %     97.5 %
## (Intercept)       9.2060707 11.9244526
## bill_length_mm    0.1656635  0.2352227
## speciesChinstrap -2.3771120 -1.4890438
## speciesGentoo    -5.4857298 -4.7209009</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="statistical-inference.html#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="co"># By default the 95% confidence intervals are returned </span></span>
<span id="cb158-2"><a href="statistical-inference.html#cb158-2" aria-hidden="true" tabindex="-1"></a><span class="co"># you can change this using the `level = ` argument</span></span></code></pre></div>
<ul>
<li><p>This tells us that for every 1 mm increase in bill length we are 95% confident the expected bill depth will increase between 0.166 and 0.235 mm (3 sf).</p></li>
<li><p>We are 95% confident that the average bill depth of a Chinstrap penguin is between
1.5 and 2.4 mm shallower than the Adelie penguin.</p></li>
</ul>
<p>To interpret these correctly we must understand what they are telling us. That is, <strong>95% of the time, our 95% confidence intervals taken from a random sample will contain the true population parameter we are wanting to estimate.</strong></p>
<p><a href="https://rpsychologist.com/d3/ci/" title="Interpreting Confidence intervals">Check out this cool visualisation of CI’s</a></p>
</div>
<div id="point-prediction" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Point prediction<a href="statistical-inference.html#point-prediction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using the <code>slm_sp</code> model we can make a point prediction for the expected bill depth (mm) for Gentoo penguins with a bill length of 50mm.</p>
<p>Recall the model equation</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{bill\_depth\_mm} &amp;= \alpha + \beta_{1}(\operatorname{bill\_length\_mm}) + \beta_{2}(\operatorname{species}_{\operatorname{Chinstrap}}) + \beta_{3}(\operatorname{species}_{\operatorname{Gentoo}})\ + \\
&amp;\quad \epsilon
\end{aligned}
\]</span></p>
<p>And recall the output table from this model, with estimates.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="statistical-inference.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slm_sp)<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##                    Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)      10.5652616 0.69092642  15.291442 2.977289e-40
## bill_length_mm    0.2004431 0.01767974  11.337449 2.258955e-25
## speciesChinstrap -1.9330779 0.22571878  -8.564099 4.259893e-16
## speciesGentoo    -5.1033153 0.19439523 -26.252267 1.043789e-82</code></pre>
<p>We can then substitute in the values (using our dummy variable coding for <code>species</code>):</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{bill depth}} &amp; = \hat{\alpha} + \hat{\beta_1}*50 + \hat{\beta_2}*0 + \hat{\beta_3}*1\\
\ &amp; = 10.56 + 0.20*50 - 1.93*0- 5.10*1\\
\ &amp; = 10.56 + 10 - 5.10\\
\ &amp; = 15.46\text{mm}
\end{aligned}
\]</span></p>
<p>Rather than <em>by hand</em> we can do this easily in <code>R</code></p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="statistical-inference.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="do">## create new data frame with data we want to predict</span></span>
<span id="cb161-2"><a href="statistical-inference.html#cb161-2" aria-hidden="true" tabindex="-1"></a><span class="do">## the names have to match those in our original data frame</span></span>
<span id="cb161-3"><a href="statistical-inference.html#cb161-3" aria-hidden="true" tabindex="-1"></a>newdf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">species =</span> <span class="st">&quot;Gentoo&quot;</span>, <span class="at">bill_length_mm =</span> <span class="dv">50</span>)</span>
<span id="cb161-4"><a href="statistical-inference.html#cb161-4" aria-hidden="true" tabindex="-1"></a><span class="do">## use predict() function</span></span>
<span id="cb161-5"><a href="statistical-inference.html#cb161-5" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(slm_sp, <span class="at">newdata =</span> newdf) <span class="do">## more accurate than our by hand version!</span></span></code></pre></div>
<pre><code>##       1 
## 15.4841</code></pre>
<p>What does this look like on a plot</p>
<p><img src="BIOSCI220_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
</div>
</div>
<div id="tldr-lm" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> TL;DR <code>lm()</code><a href="statistical-inference.html#tldr-lm" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table>
<colgroup>
<col width="44%" />
<col width="37%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th>Traditional name</th>
<th align="center">Model formula</th>
<th align="right">R code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple regression</td>
<td align="center"><span class="math inline">\(Y \sim X_{continuous}\)</span></td>
<td align="right"><code>lm(Y ~ X)</code></td>
</tr>
<tr class="even">
<td>One-way ANOVA</td>
<td align="center"><span class="math inline">\(Y \sim X_{categorical}\)</span></td>
<td align="right"><code>lm(Y ~ X)</code></td>
</tr>
<tr class="odd">
<td>Two-way ANOVA</td>
<td align="center"><span class="math inline">\(Y \sim X1_{categorical} + X2_{categorical}\)</span></td>
<td align="right"><code>lm(Y ~ X1 + X2)</code></td>
</tr>
<tr class="even">
<td>ANCOVA</td>
<td align="center"><span class="math inline">\(Y \sim X1_{continuous} + X2_{categorical}\)</span></td>
<td align="right"><code>lm(Y ~ X1 + X2)</code></td>
</tr>
<tr class="odd">
<td>Multiple regression</td>
<td align="center"><span class="math inline">\(Y \sim X1_{continuous} + X2_{continuous}\)</span></td>
<td align="right"><code>lm(Y ~ X1 + X2)</code></td>
</tr>
<tr class="even">
<td>Factorial ANOVA</td>
<td align="center"><span class="math inline">\(Y \sim X1_{categorical} * X2_{categorical}\)</span></td>
<td align="right"><code>lm(Y ~ X1 * X2)</code> or <code>lm(Y ~ X1 + X2 + X1:X2)</code></td>
</tr>
</tbody>
</table>
<p><strong><a href="https://github.com/allisonhorst/stats-illustrations">Artwork by @allison_horst</a></strong></p>
<div class="figure">
<img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/main/other-stats-artwork/dragons.png" alt="" />
<p class="caption">Meet your MLR teaching assistants</p>
</div>
<div class="figure">
<img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/main/other-stats-artwork/dragon_regression.png" alt="" />
<p class="caption">Interpret coefficients for categorical predictor variables</p>
</div>
<div class="figure">
<img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/main/other-stats-artwork/dragons_continuous.png" alt="" />
<p class="caption">Interpret coefficients for continuous predictor variables</p>
</div>
<div class="figure">
<img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/main/other-stats-artwork/dragon_predict_mlr.png" alt="" />
<p class="caption">Make predictions using the regression model</p>
</div>
<div class="figure">
<img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/main/other-stats-artwork/dragon_residual.png" alt="" />
<p class="caption">Residuals</p>
</div>
<div class="figure">
<img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/main/other-stats-artwork/dragon_residual_distribution.png" alt="" />
<p class="caption">Check residuals for normality</p>
</div>
<div id="model-formula-syntax" class="section level3 hasAnchor" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> <strong>Model formula</strong> syntax<a href="statistical-inference.html#model-formula-syntax" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In <code>R</code> to specify the model you want to fit you typically create a model formula object; this is usually then passed as the first argument to the model fitting function (e.g., <code>lm()</code>).</p>
<p>Some notes on syntax:</p>
<p>Consider the model formula example <code>y ~ x + z + x:z</code>. There is a lot going on here:</p>
<ul>
<li>The variable to the left of <code>~</code> specifies the response, everything to the right specify the explanatory variables</li>
<li><code>+</code> indicates to include the variable to the left and right of it (it does <strong>not</strong> mean they should be summed)</li>
<li><code>:</code> denotes the interaction of the variables to its left and right</li>
</ul>
<p>Additionally, some other symbols have special meanings in model formula:</p>
<ul>
<li><p><code>*</code> means to include all main effects and interactions, so <code>a * b</code> is the same as <code>a + b + a:b</code></p></li>
<li><p><code>^</code> is used to include main effects and interactions up to a specified level. For example, <code>(a + b + c)^2</code> is equivalent to <code>a + b + c + a:b + a:c + b:c</code> (note <code>(a + b + c)^3</code> would also add <code>a:b:c</code>)</p></li>
<li><p><code>-</code> excludes terms that might otherwise be included. For example, <code>-1</code> excludes the intercept otherwise included by default, and <code>a*b - b</code> would produce <code>a + a:b</code></p></li>
</ul>
<p>Mathematical functions can also be directly used in the model formula to transform a variable directly (e.g., <code>y ~ exp(x) + log(z) + x:z</code>). One thing that may seem counter intuitive is in creating polynomial expressions (e.g., <span class="math inline">\(x^2\)</span>). Here the expression <code>y ~ x^2</code> does <strong>not</strong> relate to squaring the explanatory variable <span class="math inline">\(x\)</span> (this is to do with the syntax <code>^</code> you see above. To include <span class="math inline">\(x^2\)</span> as a term in our model we have to use the <code>I()</code> (the “as-is” operator). For example, <code>y ~ I(x^2)</code>).</p>
</div>
</div>
<div id="other-resources-optional-but-recommended-1" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Other resources: optional but recommended<a href="statistical-inference.html#other-resources-optional-but-recommended-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><a href="https://interactions.jacob-long.com/articles/interactions.html">Exploring interactions with continuous predictors in regression models</a></li>
<li><a href="https://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108">The ASA Statement on p-Values: Context, Process, and Purpose</a></li>
</ul>
</div>
<div id="beyond-linear-models-to-generalised-linear-models-glms-not-examinable" class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> Beyond Linear Models to Generalised Linear Models (GLMs) (<em>not examinable</em>)<a href="statistical-inference.html#beyond-linear-models-to-generalised-linear-models-glms-not-examinable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall the assumptions of a linear model</p>
<ul>
<li>The <span class="math inline">\(i\)</span>th observation’s response, <span class="math inline">\(Y_i\)</span>, comes from a normal distribution</li>
<li>Its mean, <span class="math inline">\(\mu_i\)</span>, is a linear combination of the explanatory terms</li>
<li>Its variance, <span class="math inline">\(\sigma^2\)</span>, is the same for all observations</li>
<li>Each observation’s response is independent of all others</li>
</ul>
<p>But, what if we want to rid ourselves from a model with normal errors?</p>
<p>The answer: Generalised Linear Models.</p>
<div id="counting-animals" class="section level3 hasAnchor" number="7.7.1">
<h3><span class="header-section-number">7.7.1</span> Counting animals…<a href="statistical-inference.html#counting-animals" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A normal distribution does not adequately describe the response, the number of animals</p>
<ul>
<li>It is a continuous distribution, but the response is discrete</li>
<li>It is symmetric, but the response is unlikely to be so</li>
<li>It is unbounded, and assumes it is plausible for the response to be negative</li>
</ul>
<p>In addition, a linear regression model typically assumes constant variance, but in this situation this unlikely to be the case.</p>
<p>So why assume a normal distribution? Let’s use a Poisson distribution instead.</p>
<p><span class="math display">\[\begin{equation*}    
    \mu_i = \beta_0 + \beta_1 x_i,
  \end{equation*}\]</span></p>
<p>So
<span class="math display">\[\begin{equation*}
    Y_i \sim \text{Normal}(\mu_i\, \sigma^2),
  \end{equation*}\]</span></p>
<p>becomes</p>
<p><span class="math display">\[\begin{equation*}
    Y_i \sim \text{Poisson}(\mu_i),
\end{equation*}\]</span></p>
<p>The Poisson distribution is commonly used as a general-purpose distribution for counts. A key feature of this distribution is <span class="math inline">\(\text{Var}(Y_i) = \mu_i\)</span>, so we expect the variance to increase with the mean.</p>
</div>
<div id="other-modelling-approaches-not-examinable" class="section level3 hasAnchor" number="7.7.2">
<h3><span class="header-section-number">7.7.2</span> Other modelling approaches (not examinable)<a href="statistical-inference.html#other-modelling-approaches-not-examinable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<colgroup>
<col width="38%" />
<col width="61%" />
</colgroup>
<thead>
<tr class="header">
<th><code>R</code> function</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>glm()</code></td>
<td>Fit a linear model with a specific error structure specified using the <code>family =</code> argument (Poisson, binomial, gamma)</td>
</tr>
<tr class="even">
<td><code>gam()</code></td>
<td>Fit a generalised additive model. The R package <code>mgcv</code> must be loaded</td>
</tr>
<tr class="odd">
<td><code>lme()</code> and <code>nlme()</code></td>
<td>Fit linear and non-linear mixed effects models. The R package <code>nlme</code> must be loaded</td>
</tr>
<tr class="even">
<td><code>lmer()</code></td>
<td>Fit linear and generalised linear and non-linear mixed effects models. The package <code>lme4</code> must be installed and loaded</td>
</tr>
<tr class="odd">
<td><code>gls()</code></td>
<td>Fit generalised least squares models. The R package <code>nlme</code> must be loaded</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hypothesis-testing-and-introduction-to-linear-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multivariate-data-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["BIOSCI220.html"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
